### PR TITLE
Testing with pylint

### PR DESCRIPTION
**Pull request by SVilgelm**
Add .pylintrc and pylint command for tox
Run pylint check on travis-ci

Depends-On: #12

### CODE REVIEW

**Comment by SVilgelm** [comment]
Here is pylint report for master branch:

```08:57:44$ tox -epylint
pylint recreate: .../tungsten-tempest/.tox/pylint
pylint installdeps: -r.../tungsten-tempest/test-requirements.txt
pylint develop-inst: .../tungsten-tempest
pylint installed: .../tungsten-tempest/.tox/pylint/bin/../lib/python3.7/site.py:165: DeprecationWarning: 'U' mode is deprecated,  f = open(fullname, "rU"),.../tungsten-tempest/.tox/pylint/lib/python3.7/distutils/__init__.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses,  import imp,.../tungsten-tempest/.tox/pylint/lib/python3.7/site-packages/pip/_vendor/html5lib/_trie/_base.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working,  from collections import Mapping,asn1crypto==0.24.0,astroid==2.1.0,attrs==18.2.0,Babel==2.6.0,bcrypt==3.1.4,certifi==2018.11.29,cffi==1.11.5,chardet==3.0.4,cliff==2.14.0,cmd2==0.9.6,colorama==0.4.1,cryptography==2.4.2,debtcollector==1.20.0,extras==1.0.0,fasteners==0.14.1,fixtures==3.0.0,flake8==2.6.2,future==0.17.1,hacking==1.1.0,idna==2.7,iso8601==0.1.12,isort==4.3.4,jsonschema==2.6.0,lazy-object-proxy==1.3.1,linecache2==1.0.0,mccabe==0.6.1,monotonic==1.5,msgpack==0.6.0,netaddr==0.7.19,netifaces==0.10.7,oslo.concurrency==3.29.0,oslo.config==6.7.0,oslo.context==2.22.0,oslo.i18n==3.23.0,oslo.log==3.42.0,oslo.policy==1.42.0,oslo.serialization==2.28.1,oslo.utils==3.38.0,paramiko==2.4.2,patrole==0.4.0,pbr==5.1.1,prettytable==0.7.2,pyasn1==0.4.4,pycodestyle==2.0.0,pycparser==2.19,pyflakes==1.2.3,pylint==2.2.2,PyNaCl==1.3.0,pyparsing==2.3.0,pyperclip==1.7.0,python-dateutil==2.7.5,python-mimeparse==1.6.0,python-subunit==1.3.0,pytz==2018.7,PyYAML==3.13,requests==2.20.1,rfc3986==1.1.0,six==1.11.0,stestr==2.2.0,stevedore==1.30.0,tempest==19.0.0,testtools==2.3.0,traceback2==1.4.0,-e git+git@github.com:tungstenfabric/tungsten-tempest.git@4d85538b1b5be2de0d42c292d28a575ff72e9595#egg=tungsten_tempest,unittest2==1.1.0,urllib3==1.24.1,voluptuous==0.11.5,wcwidth==0.1.7,wrapt==1.10.11
pylint runtests: PYTHONHASHSEED='1014679521'
pylint runtests: commands[0] | pylint tungsten_tempest_plugin
.../tungsten-tempest/.tox/pylint/bin/../lib/python3.7/site.py:165: DeprecationWarning: 'U' mode is deprecated
  f = open(fullname, "rU")
.../tungsten-tempest/.tox/pylint/lib/python3.7/site-packages/astroid/interpreter/_import/spec.py:12: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
.../tungsten-tempest/.tox/pylint/lib/python3.7/site-packages/isort/pie_slice.py:362: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  class OrderedSet(collections.MutableSet):
.../tungsten-tempest/.tox/pylint/lib/python3.7/site-packages/pylint/reporters/text.py:174: DeprecationWarning: parseable output format is deprecated. This is equivalent to --msg-template={path}:{line}: [{msg_id}({symbol}), {obj}] {msg}
  DeprecationWarning,

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

_________________________________________________________________________________________________ summary __________________________________________________________________________________________________
  pylint: commands succeeded
  congratulations :)```

**Comment by SVilgelm** [comment]
Here is pep8,pylint and py27 report:
```
09:08:06$ tox -epep8,pylint,py27
pep8 recreate: .../tungsten-tempest/.tox/pep8
pep8 installdeps: -r.../tungsten-tempest/test-requirements.txt
pep8 develop-inst: .../tungsten-tempest
pep8 installed: .../tungsten-tempest/.tox/pep8/bin/../lib/python3.7/site.py:165: DeprecationWarning: 'U' mode is deprecated,  f = open(fullname, "rU"),.../tungsten-tempest/.tox/pep8/lib/python3.7/distutils/__init__.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses,  import imp,.../tungsten-tempest/.tox/pep8/lib/python3.7/site-packages/pip/_vendor/html5lib/_trie/_base.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working,  from collections import Mapping,asn1crypto==0.24.0,astroid==2.1.0,attrs==18.2.0,Babel==2.6.0,bcrypt==3.1.4,certifi==2018.11.29,cffi==1.11.5,chardet==3.0.4,cliff==2.14.0,cmd2==0.9.6,colorama==0.4.1,cryptography==2.4.2,debtcollector==1.20.0,extras==1.0.0,fasteners==0.14.1,fixtures==3.0.0,flake8==2.6.2,future==0.17.1,hacking==1.1.0,idna==2.7,iso8601==0.1.12,isort==4.3.4,jsonschema==2.6.0,lazy-object-proxy==1.3.1,linecache2==1.0.0,mccabe==0.6.1,monotonic==1.5,msgpack==0.6.0,netaddr==0.7.19,netifaces==0.10.7,oslo.concurrency==3.29.0,oslo.config==6.7.0,oslo.context==2.22.0,oslo.i18n==3.23.0,oslo.log==3.42.0,oslo.policy==1.42.0,oslo.serialization==2.28.1,oslo.utils==3.38.0,paramiko==2.4.2,patrole==0.4.0,pbr==5.1.1,prettytable==0.7.2,pyasn1==0.4.4,pycodestyle==2.0.0,pycparser==2.19,pyflakes==1.2.3,pylint==2.2.2,PyNaCl==1.3.0,pyparsing==2.3.0,pyperclip==1.7.0,python-dateutil==2.7.5,python-mimeparse==1.6.0,python-subunit==1.3.0,pytz==2018.7,PyYAML==3.13,requests==2.20.1,rfc3986==1.1.0,six==1.11.0,stestr==2.2.0,stevedore==1.30.0,tempest==19.0.0,testtools==2.3.0,traceback2==1.4.0,-e git+git@github.com:tungstenfabric/tungsten-tempest.git@204d90c74a0bb14d0dadf1e91dc826929b890b37#egg=tungsten_tempest,unittest2==1.1.0,urllib3==1.24.1,voluptuous==0.11.5,wcwidth==0.1.7,wrapt==1.10.11
pep8 runtests: PYTHONHASHSEED='498004114'
pep8 runtests: commands[0] | flake8
.../tungsten-tempest/.tox/pep8/bin/../lib/python3.7/site.py:165: DeprecationWarning: 'U' mode is deprecated
  f = open(fullname, "rU")
.../tungsten-tempest/.tox/pep8/lib/python3.7/site-packages/pycodestyle.py:111: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
.../tungsten-tempest/.tox/pep8/lib/python3.7/distutils/__init__.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
pep8 runtests: commands[1] | check-uuid --package tungsten_tempest_plugin.tests.api
.../tungsten-tempest/.tox/pep8/bin/../lib/python3.7/site.py:165: DeprecationWarning: 'U' mode is deprecated
  f = open(fullname, "rU")
.../tungsten-tempest/.tox/pep8/lib/python3.7/site-packages/oslo_config/cfg.py:1913: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  class ConfigOpts(collections.Mapping):
.../tungsten-tempest/.tox/pep8/lib/python3.7/site-packages/babel/localedata.py:17: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
.../tungsten-tempest/.tox/pep8/lib/python3.7/distutils/__init__.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
.../tungsten-tempest/.tox/pep8/lib/python3.7/site-packages/jsonschema/compat.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping, Sequence  # noqa
2018-12-06 09:09:09.358 14118 INFO tempest [-] Using tempest config file /etc/tempest/tempest.conf
pylint develop-inst-nodeps: .../tungsten-tempest
pylint installed: .../tungsten-tempest/.tox/pylint/bin/../lib/python3.7/site.py:165: DeprecationWarning: 'U' mode is deprecated,  f = open(fullname, "rU"),.../tungsten-tempest/.tox/pylint/lib/python3.7/distutils/__init__.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses,  import imp,.../tungsten-tempest/.tox/pylint/lib/python3.7/site-packages/pip/_vendor/html5lib/_trie/_base.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working,  from collections import Mapping,asn1crypto==0.24.0,astroid==2.1.0,attrs==18.2.0,Babel==2.6.0,bcrypt==3.1.4,certifi==2018.11.29,cffi==1.11.5,chardet==3.0.4,cliff==2.14.0,cmd2==0.9.6,colorama==0.4.1,cryptography==2.4.2,debtcollector==1.20.0,extras==1.0.0,fasteners==0.14.1,fixtures==3.0.0,flake8==2.6.2,future==0.17.1,hacking==1.1.0,idna==2.7,iso8601==0.1.12,isort==4.3.4,jsonschema==2.6.0,lazy-object-proxy==1.3.1,linecache2==1.0.0,mccabe==0.6.1,monotonic==1.5,msgpack==0.6.0,netaddr==0.7.19,netifaces==0.10.7,oslo.concurrency==3.29.0,oslo.config==6.7.0,oslo.context==2.22.0,oslo.i18n==3.23.0,oslo.log==3.42.0,oslo.policy==1.42.0,oslo.serialization==2.28.1,oslo.utils==3.38.0,paramiko==2.4.2,patrole==0.4.0,pbr==5.1.1,prettytable==0.7.2,pyasn1==0.4.4,pycodestyle==2.0.0,pycparser==2.19,pyflakes==1.2.3,pylint==2.2.2,PyNaCl==1.3.0,pyparsing==2.3.0,pyperclip==1.7.0,python-dateutil==2.7.5,python-mimeparse==1.6.0,python-subunit==1.3.0,pytz==2018.7,PyYAML==3.13,requests==2.20.1,rfc3986==1.1.0,six==1.11.0,stestr==2.2.0,stevedore==1.30.0,tempest==19.0.0,testtools==2.3.0,traceback2==1.4.0,-e git+git@github.com:tungstenfabric/tungsten-tempest.git@204d90c74a0bb14d0dadf1e91dc826929b890b37#egg=tungsten_tempest,unittest2==1.1.0,urllib3==1.24.1,voluptuous==0.11.5,wcwidth==0.1.7,wrapt==1.10.11
pylint runtests: PYTHONHASHSEED='498004114'
pylint runtests: commands[0] | pylint tungsten_tempest_plugin
.../tungsten-tempest/.tox/pylint/bin/../lib/python3.7/site.py:165: DeprecationWarning: 'U' mode is deprecated
  f = open(fullname, "rU")
.../tungsten-tempest/.tox/pylint/lib/python3.7/site-packages/astroid/interpreter/_import/spec.py:12: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
.../tungsten-tempest/.tox/pylint/lib/python3.7/site-packages/isort/pie_slice.py:362: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  class OrderedSet(collections.MutableSet):
.../tungsten-tempest/.tox/pylint/lib/python3.7/site-packages/pylint/reporters/text.py:174: DeprecationWarning: parseable output format is deprecated. This is equivalent to --msg-template={path}:{line}: [{msg_id}({symbol}), {obj}] {msg}
  DeprecationWarning,

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

py27 develop-inst-nodeps: .../tungsten-tempest
py27 installed: asn1crypto==0.24.0,astroid==1.6.5,Babel==2.6.0,backports.functools-lru-cache==1.5,bcrypt==3.1.4,certifi==2018.11.29,cffi==1.11.5,chardet==3.0.4,cliff==2.14.0,cmd2==0.8.9,configparser==3.5.0,contextlib2==0.5.5,cryptography==2.4.2,debtcollector==1.20.0,enum34==1.1.6,extras==1.0.0,fasteners==0.14.1,fixtures==3.0.0,flake8==2.6.2,funcsigs==1.0.2,functools32==3.2.3.post2,future==0.17.1,futures==3.2.0,hacking==1.1.0,idna==2.7,ipaddress==1.0.22,iso8601==0.1.12,isort==4.3.4,jsonschema==2.6.0,lazy-object-proxy==1.3.1,linecache2==1.0.0,mccabe==0.6.1,monotonic==1.5,msgpack==0.6.0,netaddr==0.7.19,netifaces==0.10.7,oslo.concurrency==3.29.0,oslo.config==6.7.0,oslo.context==2.22.0,oslo.i18n==3.23.0,oslo.log==3.41.0,oslo.policy==1.41.1,oslo.serialization==2.28.1,oslo.utils==3.37.1,paramiko==2.4.2,patrole==0.4.0,pbr==5.1.1,prettytable==0.7.2,pyasn1==0.4.4,pycodestyle==2.0.0,pycparser==2.19,pyflakes==1.2.3,pylint==1.9.3,PyNaCl==1.3.0,pyparsing==2.3.0,pyperclip==1.7.0,python-dateutil==2.7.5,python-mimeparse==1.6.0,python-subunit==1.3.0,pytz==2018.7,PyYAML==3.13,requests==2.20.1,rfc3986==1.1.0,singledispatch==3.4.0.3,six==1.11.0,stestr==2.2.0,stevedore==1.30.0,subprocess32==3.5.3,tempest==19.0.0,testtools==2.3.0,traceback2==1.4.0,-e git+git@github.com:tungstenfabric/tungsten-tempest.git@204d90c74a0bb14d0dadf1e91dc826929b890b37#egg=tungsten_tempest,unicodecsv==0.14.1,unittest2==1.1.0,urllib3==1.24.1,voluptuous==0.11.5,wcwidth==0.1.7,wrapt==1.10.11
py27 runtests: PYTHONHASHSEED='498004114'
py27 runtests: commands[0] | find . -type f -name '*.pyc' -delete
_________________________________________________________________________________________________ summary __________________________________________________________________________________________________
  pep8: commands succeeded
  pylint: commands succeeded
  py27: commands succeeded
  congratulations :)```

**Comment by SVilgelm** [comment]
@pcarver what about this one? I think we can merge

**Comment by pcarver** [comment]
@SVilgelm I believe @aveeshek wanted to discuss this one with you. He indicated it may not be what we want.

**Comment by SVilgelm** [comment]
ok

**Comment by aveeshek** [comment]
Why do we really need pylintrc file here? Can we simply not run against the default one? Default upstream pylintrc was the initial idea here.

**Comment by SVilgelm** [comment]
Avishek, do you have a link for the pylintrc you  want to use? It’s default with small modifications.

--
Sergey Vilgelm
https://www.vilgelm.info

**Comment by SVilgelm** [comment]
closing due to the fact that it is not necessary in upstream

**Pull request closed without merging**
