### PR TITLE
Add tests for fabric-namespaces and fabric

### PR DESCRIPTION
**Pull request by SVilgelm**
Also generic contrail_client that should replace all insanity that is
going on in services.contrail.json.*_client

http://www.opencontrail.org/documentation/api/r5.0/contrail_openapi.html#fabric
http://www.opencontrail.org/documentation/api/r5.0/contrail_openapi.html#fabric-namespace

Change-Id: I6f0d2034ece8f2d5dbd2272934711082b1686d8d
Depends-On: https://gerrit.mtn5.cci.att.com/#/c/52538/

This commit was already tested and merged: https://gerrit.mtn5.cci.att.com/#/c/52330/

### CODE REVIEW

**Comment by SVilgelm** [comment]
Regenerated UUID of tests as they were duplicated

**Comment by SVilgelm** [comment]
You are so fast, I just wanted to rebase it to have the checks executed :)

**Comment by pcarver** [comment]
Oops, sorry. Your other comment reminded me that @aveeshek had said he was ok with this one, and since I had reviewed it two days ago I figured it was time to merge it.

**Comment by SVilgelm** [comment]
No worries, anyway the travis-ci runs the checks on the master branch and it's passed.

**Pull request merged**
